# Site settings
author: J. Ruehle
title: Research & Discovery
header-img: img/home-bg.png
email: jela07@gmail.com
copyright_name: J. Ruehle
description: > # this means to ignore newlines until "baseurl:"
  Notes along my coding journey.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jeniseruehle

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
